// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: docs.proto

package docs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDocumentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content  string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tags     []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Category string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *CreateDocumentReq) Reset() {
	*x = CreateDocumentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDocumentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentReq) ProtoMessage() {}

func (x *CreateDocumentReq) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentReq.ProtoReflect.Descriptor instead.
func (*CreateDocumentReq) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDocumentReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDocumentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDocumentReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateDocumentReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateDocumentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content  string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tags     []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Category string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Author   string   `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *CreateDocumentRes) Reset() {
	*x = CreateDocumentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDocumentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRes) ProtoMessage() {}

func (x *CreateDocumentRes) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRes.ProtoReflect.Descriptor instead.
func (*CreateDocumentRes) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDocumentRes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDocumentRes) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDocumentRes) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateDocumentRes) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateDocumentRes) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type GetDocumentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *GetDocumentReq) Reset() {
	*x = GetDocumentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDocumentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentReq) ProtoMessage() {}

func (x *GetDocumentReq) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentReq.ProtoReflect.Descriptor instead.
func (*GetDocumentReq) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{2}
}

func (x *GetDocumentReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetDocumentReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetDocumentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title       string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content     string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tags        []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Category    string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Author      string   `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	LastUpdated string   `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
}

func (x *GetDocumentRes) Reset() {
	*x = GetDocumentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDocumentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRes) ProtoMessage() {}

func (x *GetDocumentRes) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRes.ProtoReflect.Descriptor instead.
func (*GetDocumentRes) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentRes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetDocumentRes) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetDocumentRes) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetDocumentRes) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetDocumentRes) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *GetDocumentRes) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

type GetAllDocumentsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *GetAllDocumentsReq) Reset() {
	*x = GetAllDocumentsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDocumentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDocumentsReq) ProtoMessage() {}

func (x *GetAllDocumentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDocumentsReq.ProtoReflect.Descriptor instead.
func (*GetAllDocumentsReq) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllDocumentsReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAllDocumentsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Documents []*GetDocumentRes `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
}

func (x *GetAllDocumentsRes) Reset() {
	*x = GetAllDocumentsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllDocumentsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDocumentsRes) ProtoMessage() {}

func (x *GetAllDocumentsRes) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDocumentsRes.ProtoReflect.Descriptor instead.
func (*GetAllDocumentsRes) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllDocumentsRes) GetDocuments() []*GetDocumentRes {
	if x != nil {
		return x.Documents
	}
	return nil
}

type UpdateDocumentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content  string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tags     []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Category string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *UpdateDocumentReq) Reset() {
	*x = UpdateDocumentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDocumentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentReq) ProtoMessage() {}

func (x *UpdateDocumentReq) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentReq.ProtoReflect.Descriptor instead.
func (*UpdateDocumentReq) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDocumentReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDocumentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateDocumentReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateDocumentReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UpdateDocumentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateDocumentRes) Reset() {
	*x = UpdateDocumentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDocumentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRes) ProtoMessage() {}

func (x *UpdateDocumentRes) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRes.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRes) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDocumentRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteDocumentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *DeleteDocumentReq) Reset() {
	*x = DeleteDocumentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDocumentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentReq) ProtoMessage() {}

func (x *DeleteDocumentReq) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentReq.ProtoReflect.Descriptor instead.
func (*DeleteDocumentReq) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDocumentReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DeleteDocumentReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DeleteDocumentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteDocumentRes) Reset() {
	*x = DeleteDocumentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDocumentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRes) ProtoMessage() {}

func (x *DeleteDocumentRes) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRes.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRes) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDocumentRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShareDocumentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title          string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	RecipientEmail string `protobuf:"bytes,2,opt,name=recipient_email,json=recipientEmail,proto3" json:"recipient_email,omitempty"`
	Permissions    string `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
}

func (x *ShareDocumentReq) Reset() {
	*x = ShareDocumentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareDocumentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareDocumentReq) ProtoMessage() {}

func (x *ShareDocumentReq) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareDocumentReq.ProtoReflect.Descriptor instead.
func (*ShareDocumentReq) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{10}
}

func (x *ShareDocumentReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShareDocumentReq) GetRecipientEmail() string {
	if x != nil {
		return x.RecipientEmail
	}
	return ""
}

func (x *ShareDocumentReq) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

type ShareDocumentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ShareDocumentRes) Reset() {
	*x = ShareDocumentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareDocumentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareDocumentRes) ProtoMessage() {}

func (x *ShareDocumentRes) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareDocumentRes.ProtoReflect.Descriptor instead.
func (*ShareDocumentRes) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{11}
}

func (x *ShareDocumentRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchDocumentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SearchDocumentReq) Reset() {
	*x = SearchDocumentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchDocumentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDocumentReq) ProtoMessage() {}

func (x *SearchDocumentReq) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDocumentReq.ProtoReflect.Descriptor instead.
func (*SearchDocumentReq) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{12}
}

func (x *SearchDocumentReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchDocumentReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SearchDocumentRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Documents []*GetDocumentRes `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
}

func (x *SearchDocumentRes) Reset() {
	*x = SearchDocumentRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchDocumentRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDocumentRes) ProtoMessage() {}

func (x *SearchDocumentRes) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDocumentRes.ProtoReflect.Descriptor instead.
func (*SearchDocumentRes) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{13}
}

func (x *SearchDocumentRes) GetDocuments() []*GetDocumentRes {
	if x != nil {
		return x.Documents
	}
	return nil
}

var File_docs_proto protoreflect.FileDescriptor

var file_docs_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x6f,
	0x63, 0x73, 0x22, 0x73, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x8b, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x3c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x22, 0xab, 0x01, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x21,
	0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x22, 0x2a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x48, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x52, 0x09, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x73, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x2d, 0x0a, 0x11,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2d, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x73, 0x0a, 0x10, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x20,
	0x0a, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x2c, 0x0a, 0x10, 0x53, 0x68, 0x61, 0x72, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3f,
	0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0x47, 0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x52, 0x09, 0x64,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x32, 0xe0, 0x03, 0x0a, 0x0b, 0x44, 0x6f, 0x63,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x64, 0x6f, 0x63,
	0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x64, 0x6f,
	0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x14, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x64, 0x6f, 0x63,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x12, 0x42,
	0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x17, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x64, 0x6f, 0x63, 0x73,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x12, 0x42, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x64, 0x6f, 0x63, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x0d, 0x53, 0x68, 0x61, 0x72, 0x65, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x53,
	0x68, 0x61, 0x72, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x65, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x64, 0x6f, 0x63, 0x73,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x67,
	0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x6f, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_docs_proto_rawDescOnce sync.Once
	file_docs_proto_rawDescData = file_docs_proto_rawDesc
)

func file_docs_proto_rawDescGZIP() []byte {
	file_docs_proto_rawDescOnce.Do(func() {
		file_docs_proto_rawDescData = protoimpl.X.CompressGZIP(file_docs_proto_rawDescData)
	})
	return file_docs_proto_rawDescData
}

var file_docs_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_docs_proto_goTypes = []any{
	(*CreateDocumentReq)(nil),  // 0: docs.CreateDocumentReq
	(*CreateDocumentRes)(nil),  // 1: docs.CreateDocumentRes
	(*GetDocumentReq)(nil),     // 2: docs.GetDocumentReq
	(*GetDocumentRes)(nil),     // 3: docs.GetDocumentRes
	(*GetAllDocumentsReq)(nil), // 4: docs.GetAllDocumentsReq
	(*GetAllDocumentsRes)(nil), // 5: docs.GetAllDocumentsRes
	(*UpdateDocumentReq)(nil),  // 6: docs.UpdateDocumentReq
	(*UpdateDocumentRes)(nil),  // 7: docs.UpdateDocumentRes
	(*DeleteDocumentReq)(nil),  // 8: docs.DeleteDocumentReq
	(*DeleteDocumentRes)(nil),  // 9: docs.DeleteDocumentRes
	(*ShareDocumentReq)(nil),   // 10: docs.ShareDocumentReq
	(*ShareDocumentRes)(nil),   // 11: docs.ShareDocumentRes
	(*SearchDocumentReq)(nil),  // 12: docs.SearchDocumentReq
	(*SearchDocumentRes)(nil),  // 13: docs.SearchDocumentRes
}
var file_docs_proto_depIdxs = []int32{
	3,  // 0: docs.GetAllDocumentsRes.documents:type_name -> docs.GetDocumentRes
	3,  // 1: docs.SearchDocumentRes.documents:type_name -> docs.GetDocumentRes
	0,  // 2: docs.DocsService.CreateDocument:input_type -> docs.CreateDocumentReq
	2,  // 3: docs.DocsService.GetDocument:input_type -> docs.GetDocumentReq
	4,  // 4: docs.DocsService.GetAllDocuments:input_type -> docs.GetAllDocumentsReq
	6,  // 5: docs.DocsService.UpdateDocument:input_type -> docs.UpdateDocumentReq
	8,  // 6: docs.DocsService.DeleteDocument:input_type -> docs.DeleteDocumentReq
	10, // 7: docs.DocsService.ShareDocument:input_type -> docs.ShareDocumentReq
	12, // 8: docs.DocsService.SearchDocument:input_type -> docs.SearchDocumentReq
	1,  // 9: docs.DocsService.CreateDocument:output_type -> docs.CreateDocumentRes
	3,  // 10: docs.DocsService.GetDocument:output_type -> docs.GetDocumentRes
	5,  // 11: docs.DocsService.GetAllDocuments:output_type -> docs.GetAllDocumentsRes
	7,  // 12: docs.DocsService.UpdateDocument:output_type -> docs.UpdateDocumentRes
	9,  // 13: docs.DocsService.DeleteDocument:output_type -> docs.DeleteDocumentRes
	11, // 14: docs.DocsService.ShareDocument:output_type -> docs.ShareDocumentRes
	13, // 15: docs.DocsService.SearchDocument:output_type -> docs.SearchDocumentRes
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_docs_proto_init() }
func file_docs_proto_init() {
	if File_docs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_docs_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDocumentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDocumentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetDocumentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetDocumentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllDocumentsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllDocumentsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDocumentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDocumentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteDocumentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteDocumentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ShareDocumentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ShareDocumentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*SearchDocumentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SearchDocumentRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_docs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_goTypes,
		DependencyIndexes: file_docs_proto_depIdxs,
		MessageInfos:      file_docs_proto_msgTypes,
	}.Build()
	File_docs_proto = out.File
	file_docs_proto_rawDesc = nil
	file_docs_proto_goTypes = nil
	file_docs_proto_depIdxs = nil
}
